### ISSUE TITLE
CloudKeyPro+ no connection - unifi OS

### ISSUE THREAD

**Issue by hdnhdn** [LoxYourLife/unifi-presence#7]
i have teste the connection to dream machine und cloudkey+ 
both not working on 6.5.51 network controller.

whe i will connect. the text saving data is shown but no connection can be saved.
on open the plugin it needs 5 minutes to see die configuration page..

ist there an option to get work?

**Comment by Scyks** [comment]
The plugin requires network controller version 6.5.54. could you please upgrade your network controller and try again?

**Comment by hdnhdn** [comment]
curios the plugin say > 6.4.54 i have 6.5.51. you post 6.5.54 that are not released?

**Comment by Scyks** [comment]
You are right, my bad. It's 6.4.54.
Could be that they have changed the interface again. In the release notes are some hints:
* Improve client name display.
* Improve clients page performance with lots of Offline clients.

Let me try to update my network controller.

**Comment by hdnhdn** [comment]
i think the problem are the cloudkey instead of dream machine but they have the same unifi os so it must be no different..
i cannot downgrade i have test it with console command line ssh but nothing work to downgrade.

i will use this cool plugin for my loxone..

**Comment by Scyks** [comment]
Could be. Do you need a port to access the network?
Can you provide the url to your networks client page? Mine is https://10.10.0.1/network/default/clients

Could also be that you don't use the default site, there is already a feature request for setting up the site.

Unfortunatelly I cannot upgrade my Network, it says "up to date" .
But there is a new version available ... i'm confused.

**Comment by hdnhdn** [comment]
what i have test.

i use same as dreammachine unifi os. i have not port on theis, the unifi os linked directyl
https://10.10.1.249/network/nfyju86w/dashboard
default page i have delete and set my sit to default in putty as descriptet. but the doesnt work with default and withouth default page. so at moment i have only 1 site an this is set to default.

you can update if you set the chanell to previos or beta.
but the new controller is releaset official.

you can upgrad by command line ssh..

i think the change the api ..

**Comment by Scyks** [comment]
I guess the issue is that you use a different site name than default. yours is "nfyju86w" instead of "default". That's currently not supported from the plugin.

If you`re familiar with ssh, you can try to fix it yourself for now:
* Login to your loxberry via ssh
* cd bin/plugins/unifi_presence
* edit `lib/Unifi.js` and replace every occurrence of `default` to `nfyju86w` from line 66 till 82 and save the file
* run `npm run restart` and pray to god 😂 

Otherwise you need to wait until i've time to implement this request to specify the site name.

**Comment by hdnhdn** [comment]
i have change the site name but that doesnt help the plugis says that my version of controller is 0 ..
there must be another change..

**Comment by hdnhdn** [comment]
i have found the problem. the site name isnt i have change the site name in unifi database to default so the default name also work for my sit. the problem are the proxy varialbe in the code. i have delete this so it works..

**Comment by Scyks** [comment]
But deleting the "proxy" path is not correct. If you set "Native" in the UI on Loxberry, the path shouldn't be there.
In case of an update you have the same issue again ;)
