### ISSUE TITLE
Plugin Seite extrem langsam und keine Devices gefunden

### ISSUE THREAD

**Issue by Leitner1** [LoxYourLife/unifi-presence#8]
Der Unifi Controller läuft auf demselben RPI3B wie Loxberry.
Wenn ich die Seite des Plugins lade http://loxberry/admin/plugins/unifi_presence/, dauert dies ca. 3 Minuten.
Unifi Wifi Geräte werden vom Plugin keine gefunden. 
Alles andere läuft normal schnell. Hab den RPI auch schon neu gestartet.
Leider finde ich keine Logfiles zum Plugin.

Was kann ich tun?

LoxBerry V2.2.1.2
UniFi Presence v1.0.2
MQTT Gateway v2.0.4
Unifi Controller v6.5.53

Gruß
Leitner

**Comment by Scyks** [comment]
Hey,

Ja ich habs schon mehrfach gehört, dass es unter umständen langsam sein kann. Ist dein Controller selbst auch langsam?

Logfiles gibt es leider _noch_ nicht.

**Comment by Leitner1** [comment]
Nein der Controller läuft ganz normal.
Ich habe jetzt die SSH-Authentifizierung im Unifi Controller deaktiviert, dann ist das Plugin zwar immer noch sehr langsam, aber die WiFi Geräte werden gefunden :-).

**Comment by Scyks** [comment]
Welche IP benutzt du denn für den Controller? Ich hoffe 127.0.0.1 ;)

**Comment by Leitner1** [comment]
Ich Depp! Ursprünglich wollte ich "localhost" eingeben, war aber nicht zulässig. Dann habe ich einfach die lokale IP eingegeben, also 192.168.10.200. An 127.0.0.1 hab ich nicht gedacht :-(. Jetzt lädt das Plugin deutlich schneller 6 Sekunden anstelle von 3 Minuten :-D. Vielen Dank!

**Comment by Scyks** [comment]
Kein Problem. 6 Sekunden ist immer noch recht lange, aber das kann am Controller liegen.
